import type { Metadata } from 'next'
import { Lato } from 'next/font/google'
import NextTopLoader from 'nextjs-toploader'
import './global.css'

const Lato700 = Lato({
  weight: '700',
  preload: false,
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='ja'>
      <body className={Lato700.className}>
        <NextTopLoader />
        {children}
      </body>
    </html>
  )
}
